### PR TITLE
Fix orientation error in command when idle

### PR DESCRIPTION
**Pull request by RBinsonB**
## Basic Info
 
| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | Closes https://github.com/osrf/fleet_adapter_mir/issues/28 |
| Primary OS tested on | Ubuntu 22.04 |
| Robotic platform tested on | Real MiR100 with Open-RMF running on ROS 2 Humble |
 
---
## How to run this PR feature
* Reproduce the condition of the linked issue (https://github.com/osrf/fleet_adapter_mir/issues/28) with the MiR map and the RMF having a different angle.
* Build the MiR fleet adapter package (or mount and build on the package in the Open-RMF test docker)
* Run Open-RMF core and the MiR fleet adapter

**What you should expect:**
* The robot should move to the closest point when initialized (if the starting point is not defined in the config file).
* After moving to a point (after initialization, a task...) the robot will stay immobile. From time to time it will receive a MiR mission to move to its current location and will not move.
  * Previous behavior:

    https://user-images.githubusercontent.com/43391966/235664007-30510a19-d594-4ac0-868f-605232bfadcd.mp4

  * New behavior: 

    https://user-images.githubusercontent.com/43391966/235664029-ab349ba7-e753-4137-8136-272edd0fb69d.mp4

 
## Description of contribution in a few bullet points
* The orientation of the transform from RMF to MiR should be added (and not deducted) to the robot orientation in the RMF map frame in order to get the orientation in the MiR map frame.

### CODE REVIEW

**Review by Yadunund — APPROVED** [review]
Thanks for the PR. The change here aligns with how we calculate the yaw for the [Ecobot](https://github.com/open-rmf/fleet_adapter_ecobot/blob/d47a1d2a8370944a6ab123b5770723035cd788ca/fleet_adapter_ecobot/utils.py#L101) when converting RMF coordinates to robot coordinates.

**Comment by RBinsonB** [comment]
Alright, let's wait for https://github.com/osrf/fleet_adapter_mir/pull/27 to be merged first then.

**Comment by Yadunund** [comment]
@RBinsonB we merged #27 so could you verify if the problem is resolved?

**Comment by RBinsonB** [comment]
I merged the latest main into my branch.

I will test on the real robot next week to confirm everything is working.

**Comment by Yadunund** [comment]
Great, thanks.

**Review by Yadunund — APPROVED** [review]
Thanks for testing.

**Pull request merged**
