### PR TITLE
Feature/add fleet adapter task params

### PR DESCRIPTION
**Pull request by alexchua0108**
- Added MiRClientAPI.py instead of using MiR100client
- Added Task Planner parameter into the fleet adapter

### CODE REVIEW

**Comment by youliangtan** [comment]
Thanks for opening this PR @alexchua0108! FYI, Alex mentioned that he has been using this fleet_adapter on the actual MiR, and it's working well so far.

One catch about this PR, it is not forked from `master`, but from the `/fix/estimate_arrival` branch. This "fix" branch was developed 8 months ago by @mxgrey , and not sure if it is alright for us to merge these fix commits into master?

**Comment by mxgrey** [comment]
Thanks for opening this PR, I'm very excited to have a working MiR fleet adapter that uses the latest API.

I'm tied up with an upcoming milestone at the moment, but I'll be eager to review this as soon as that's taken care of.

@youliangtan I think it's fine to merge directly into `main` if these changes have been tested. The current `main` branch is known to not work, so we aren't really risking any harm.

**Review by aaronchongth — APPROVED** [review]
Thanks for putting this together! We can merge this in and refine it more by introducing the newer APIs from https://github.com/open-rmf/fleet_adapter_template.

**Review by youliangtan — APPROVED** [review]
Will then tag this as `v0.1.0`. Improvements related to task_v2 apis will soon be implemented.

**Comment by Yadunund** [comment]
Great work again @alexchua0108!

**Pull request merged**
